# version format
version: 1.5.{build}

os: Visual Studio 2015

platform:
  - x64

environment:
  QTDIR: C:\Qt\5.9\msvc2015_64
  matrix:
    - XPIKS_BINARY: true
    - CORE_TESTS: true
      QT_FATAL_WARNINGS: 1
    - INTEGRATION_TESTS: true
      QT_FATAL_WARNINGS: 1
    - UI_TESTS: true
      QT_FATAL_WARNINGS: 0

branches:
  # blacklist
  except:
    - gh-pages

configuration:
  - debug

# - release

# Do not build on tags (GitHub only)
skip_tags: false

skip_commits:
  message: /.*\[ci skip\]/       # Regex for matching commit message

# clone directory
clone_folder: c:\projects\xpiks

# set clone depth
clone_depth: 3                      # clone entire repository history if not defined

# appveyor cannot process cache correctly
#cache:
#  - vendors -> appveyor.yml

matrix:
  fast_finish: false
  allow_failures:
    - configuration: release

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - cmd: set PATH=%PATH%;%QTDIR%\bin
  - qmake -v

before_build:
#  - cmd: 'xcopy /s c:\projects\xpiks-deps\windows-libs\%configuration%-x64 c:\projects\xpiks\libs\%configuration%'
  - cmd: 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'
  - git fetch origin gh-pages
  - git checkout FETCH_HEAD -- api

build_script:
  - scripts\build\checkout_deps_windows.bat
  - scripts\build\build_vendors_windows.bat appveyor
  - if defined XPIKS_BINARY scripts\ci\appveyor-xpiks.bat
  - if defined CORE_TESTS scripts\ci\appveyor-core-tests.bat build
  - if defined INTEGRATION_TESTS scripts\ci\appveyor-integration-tests.bat build
  - if defined UI_TESTS scripts\ci\appveyor-ui-tests.bat build
  
test_script:
  - if defined CORE_TESTS scripts\ci\appveyor-core-tests.bat run
  - if defined INTEGRATION_TESTS scripts\ci\appveyor-integration-tests.bat run
  - if defined UI_TESTS scripts\ci\appveyor-ui-tests.bat run

on_failure:
  - ps: Get-EventLog AppVeyor -newest 10 | Format-List
  - ps: Get-ChildItem .\*.dmp | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
